FROM java:openjdk-8u111-alpine
RUN apk --no-cache add curl
HEALTHCHECK --start-period=30s --interval=5s CMD curl -f http://localhost:8080/actuator/health || exit 1
CMD java ${JAVA_OPTS} -jar customer-service-0.1.0-SNAPSHOT.jar
COPY ./target/customer-service-0.1.0-SNAPSHOT.jar .

